services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=OpenMeteo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sama
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    container_name: app
    volumes:
      - .:/src/
    depends_on:
      - postgres
    expose:
      - "8000"
    networks: 
      - main
    restart: always

networks:
  main:

volumes:
  postgres_data:
